version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gpt-image-ui:latest
    container_name: gpt-image-ui-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - BASE_PATH=/api
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_MODEL=${OPENAI_API_MODEL:-gpt-image-1}
      - CORS_ORIGIN=${CORS_ORIGIN:-https://yourdomain.com}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-60000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
    volumes:
      - uploads:/app/uploads
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network
    expose:
      - "3001"
    # Don't expose ports directly in production, use nginx reverse proxy

  nginx:
    image: nginx:alpine
    container_name: gpt-image-ui-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/build:/usr/share/nginx/html:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx-logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  uploads:
  nginx-logs:

networks:
  app-network:
    driver: bridge